### ISSUE TITLE
appcachefacts.info is now spam

### ISSUE THREAD

**Issue by bcomnes** [shinypb/appcachefacts#27]
It seems like you lost control of the [appcachefacts.info](https://web.archive.org/web/20141004054329/http://appcachefacts.info/) domain?  It points to [spam](http://appcachefacts.info/) now.

Working html here: https://web.archive.org/web/20140911203145/http://appcachefacts.info/

**Comment by hazeledmands** [comment]
I put up a mirror a little while ago too: http://appcache.offline.technology/

**Comment by bcomnes** [comment]
Ah cool!  Don't forget to update the github project url next to the description.

**Comment by paulirish** [comment]
@demands thx for the mirror. v nice of you.

@shinypb can you update the link in this GH project. I'm trying to pull request against all other links i can find.
